name: push event workflow

on:

    push:
      branches: [ i191904-dev ]
    pull_request:
      branches: [ i191904-dev ]

jobs:

    Code-Quality:
    
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pylint
            pip install black
        - name: Pylint QC Test Run
          run: pylint --disable=R,C polyglot
          continue-on-error: true
        - name: Black QC Test Run
          run: black --check polyglot
          continue-on-error: true
          
          
    Testing:
    
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install six
            pip install numpy
            pip install pyicu
            pip install pycld2
            pip install morfessor
        - name: Run Tests
          run: pytest test.py
