name: push event workflow

on:

    push:
      branches: [ i191904-dev ]
    pull_request:
      branches: [ i191904-dev ]

jobs:

    Code_Quality:
    
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
        - name: flake8 QC Test Run
          #Build will be stopped if any python syntax errors
          run : flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          
          
    testing:
    
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install six
            pip install numpy
            pip install icu
        - name: Run Tests
          run: pytest test.py
