name: workflow on push

on: 
  push:
    branches: [ i191905-dev ]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Install testing libraries
      run: pip install pytest icu
    - name: Installing runtime dependencies
      run: sudo apt install libicu-dev python3-tk -y
    - name: Testing the code
      run: pytest test.py

  formatting-and-linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install formatting libraries
      run: pip install black
    - name: Formatting the code
      run: black ./polyglot/
    - name: Install linting libraries
      run: pip install pylint
    - name: Linting the code
      run: pylint ./polyglot/

  